version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: attendance-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: attendance123
      POSTGRES_DB: attendance_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - attendance-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: attendance-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - attendance-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  attendance-network:
    driver: bridge